/*
 * CardPay REST API
 * Welcome to the CardPay REST API. The CardPay API uses HTTP verbs and a REST resources endpoint structure (see more info about REST). Request and response payloads are formatted as JSON. Merchant uses API to create payments, refunds, payouts or recurrings, check or update transaction status and get information about created transactions. In API authentication process based on OAuth 2.0 standard. For recent changes see changelog section.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import lombok.Data;

@Data

public class Item {
  @SerializedName("count")
  private Integer count = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("price")
  private BigDecimal price = null;
  
  public void setCount(Integer count) {
      this.count = count;
  }

  /**
   * @param count The count of product / service, provided to Customer. Any positive number
   * @return bean instance
   **/
  public Item count(Integer count) {
      this.count = count;
      return this;
  }

  
  public void setDescription(String description) {
      this.description = description;
  }

  /**
   * @param description The description of product / service, provided to Customer
   * @return bean instance
   **/
  public Item description(String description) {
      this.description = description;
      return this;
  }

  
  public void setName(String name) {
      this.name = name;
  }

  /**
   * @param name The name of product / service, provided to Customer
   * @return bean instance
   **/
  public Item name(String name) {
      this.name = name;
      return this;
  }

  
  public void setPrice(BigDecimal price) {
      this.price = price;
  }

  /**
   * @param price Price of product / service with dot as a decimal separator, must be less than 1 million
   * @return bean instance
   **/
  public Item price(BigDecimal price) {
      this.price = price;
      return this;
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    
    if (count != null) sb.append("    count: ").append(toIndentedString(count)).append("\n");
    if (description != null) sb.append("    description: ").append(toIndentedString(description)).append("\n");
    if (name != null) sb.append("    name: ").append(toIndentedString(name)).append("\n");
    if (price != null) sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

