/*
 * CardPay REST API
 * Welcome to the CardPay REST API. The CardPay API uses HTTP verbs and a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) resources endpoint structure (see more info about REST). Request and response payloads are formatted as JSON. Merchant uses API to create payments, refunds, payouts or recurrings, check or update transaction status and get information about created transactions. In API authentication process based on [OAuth 2.0](https://oauth.net/2/) standard. For recent changes see changelog section.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;
import lombok.Data;

@Data

public class MobilePaymentMethodListResponse {
  @SerializedName("payment_methods")
  private List<MobilePaymentMethodDataResponse> paymentMethods = null;
  
  public void setPaymentMethods(List<MobilePaymentMethodDataResponse> paymentMethods) {
      this.paymentMethods = paymentMethods;
  }

  /**
   * @param paymentMethods Mobile payment data
   * @return bean instance
   **/
  public MobilePaymentMethodListResponse paymentMethods(List<MobilePaymentMethodDataResponse> paymentMethods) {
      this.paymentMethods = paymentMethods;
      return this;
  }

  public MobilePaymentMethodListResponse addPaymentMethodsItem(MobilePaymentMethodDataResponse paymentMethodsItem) {
    if (this.paymentMethods == null) {
      this.paymentMethods = new ArrayList<>();
    }
    this.paymentMethods.add(paymentMethodsItem);
    return this;
  }


  @Override
  public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("MobilePaymentMethodListResponse( ");
     
     if (paymentMethods != null) sb.append("paymentMethods=").append(paymentMethods.toString()).append("; ");
     sb.append(")");
     return sb.toString();
  }

}

