/*
 * CardPay REST API
 * Welcome to the CardPay REST API. The CardPay API uses HTTP verbs and a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) resources endpoint structure (see more info about REST). Request and response payloads are formatted as JSON. Merchant uses API to create payments, refunds, payouts or recurrings, check or update transaction status and get information about created transactions. In API authentication process based on [OAuth 2.0](https://oauth.net/2/) standard. For recent changes see changelog section.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import lombok.Data;

@Data

public class PaymentRequestCard {
  @SerializedName("expiration")
  private String expiration = null;
  @SerializedName("holder")
  private String holder = null;
  @SerializedName("pan")
  private String pan = null;
  @SerializedName("security_code")
  private String securityCode = null;
  
  public void setExpiration(String expiration) {
      this.expiration = expiration;
  }

  /**
   * @param expiration Customer&#39;s card expiration date. Format: &#x60;mm/yyyy&#x60;
   * @return bean instance
   **/
  public PaymentRequestCard expiration(String expiration) {
      this.expiration = expiration;
      return this;
  }

  
  public void setHolder(String holder) {
      this.holder = holder;
  }

  /**
   * @param holder Customer&#39;s cardholder name. Any valid cardholder name
   * @return bean instance
   **/
  public PaymentRequestCard holder(String holder) {
      this.holder = holder;
      return this;
  }

  
  public void setPan(String pan) {
      this.pan = pan;
  }

  /**
   * @param pan Customer&#39;s card number (PAN). Any valid card number, may contain spaces
   * @return bean instance
   **/
  public PaymentRequestCard pan(String pan) {
      this.pan = pan;
      return this;
  }

  
  public void setSecurityCode(String securityCode) {
      this.securityCode = securityCode;
  }

  /**
   * @param securityCode Customer&#39;s CVV2 / CVC2 / CAV2
   * @return bean instance
   **/
  public PaymentRequestCard securityCode(String securityCode) {
      this.securityCode = securityCode;
      return this;
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequestCard {\n");
    
    if (expiration != null) sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    if (holder != null) sb.append("    holder: ").append(toIndentedString(holder)).append("\n");
    if (pan != null) sb.append("    pan: ").append(toIndentedString(pan)).append("\n");
    if (securityCode != null) sb.append("    securityCode: ").append(toIndentedString(securityCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

