/*
 * CardPay REST API
 * Welcome to the CardPay REST API. The CardPay API uses HTTP verbs and a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) resources endpoint structure (see more info about REST). Request and response payloads are formatted as JSON. Merchant uses API to create payments, refunds, payouts or recurrings, check or update transaction status and get information about created transactions. In API authentication process based on [OAuth 2.0](https://oauth.net/2/) standard. For recent changes see changelog section.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;

@Data

public class RefundResponseCustomer {
  @SerializedName("email")
  private String email = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("ip_country")
  private String ipCountry = null;
  @SerializedName("user_agent")
  private String userAgent = null;
  
  public void setEmail(String email) {
      this.email = email;
  }

  /**
   * @param email Customer&#39;s e-mail address, here can be value returned from payment method - in case then in Merchant request &#x60;customer.email&#x60; wasn&#39;t presented
   * @return bean instance
   **/
  public RefundResponseCustomer email(String email) {
      this.email = email;
      return this;
  }

  
  public void setId(String id) {
      this.id = id;
  }

  /**
   * @param id Customer&#39;s ID in Merchant&#39;s system
   * @return bean instance
   **/
  public RefundResponseCustomer id(String id) {
      this.id = id;
      return this;
  }

  
  public void setIpCountry(String ipCountry) {
      this.ipCountry = ipCountry;
  }

  /**
   * @param ipCountry Customer country by IP
   * @return bean instance
   **/
  public RefundResponseCustomer ipCountry(String ipCountry) {
      this.ipCountry = ipCountry;
      return this;
  }

  
  public void setUserAgent(String userAgent) {
      this.userAgent = userAgent;
  }

  /**
   * @param userAgent User agent
   * @return bean instance
   **/
  public RefundResponseCustomer userAgent(String userAgent) {
      this.userAgent = userAgent;
      return this;
  }


  @Override
  public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("RefundResponseCustomer( ");
     
     if (email != null) sb.append("email=").append(email.toString()).append("; ");
     if (id != null) sb.append("id=").append(id.toString()).append("; ");
     if (ipCountry != null) sb.append("ipCountry=").append(ipCountry.toString()).append("; ");
     if (userAgent != null) sb.append("userAgent=").append(userAgent.toString()).append("; ");
     sb.append(")");
     return sb.toString();
  }

}

