/*
 * CardPay REST API
 * Welcome to the CardPay REST API. The CardPay API uses HTTP verbs and a [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) resources endpoint structure (see more info about REST). Request and response payloads are formatted as JSON. Merchant uses API to create payments, refunds, payouts or recurrings, check or update transaction status and get information about created transactions. In API authentication process based on [OAuth 2.0](https://oauth.net/2/) standard. For recent changes see changelog section.
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cardpay.sdk.model;

import com.google.gson.annotations.SerializedName;
import lombok.Data;

@Data

public class TransactionResponseEWalletAccount {
  @SerializedName("holder")
  private String holder = null;
  @SerializedName("id")
  private String id = null;
  
  public void setHolder(String holder) {
      this.holder = holder;
  }

  /**
   * @param holder Ewallet account holder name For DIRECTBANKINGEU - Account holder name (optional)
   * @return bean instance
   **/
  public TransactionResponseEWalletAccount holder(String holder) {
      this.holder = holder;
      return this;
  }

  
  public void setId(String id) {
      this.id = id;
  }

  /**
   * @param id For QIWI - Customer phone number (from 1 to 15 digits) For WEBMONEY - Customer account number For NETELLER - Email address of the customer For DIRECTBANKINGNGA - Bank account number For AQRCODE - Customer account number For AIRTEL, MPESA, MTN, UGANDAMOBILE, VODAFONE, TIGO - Customer account number For &#39;Latin America&#39; - Customer’s personal identification number For DIRECTBANKINGEU - Sender IBAN (optional)
   * @return bean instance
   **/
  public TransactionResponseEWalletAccount id(String id) {
      this.id = id;
      return this;
  }


  @Override
  public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("TransactionResponseEWalletAccount( ");
     
     if (holder != null) sb.append("holder=").append(holder.toString()).append("; ");
     if (id != null) sb.append("id=").append(id.toString()).append("; ");
     sb.append(")");
     return sb.toString();
  }

}

